# Generated by Django 4.1 on 2023-01-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facultyExecutivebodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial', models.IntegerField(null=True)),
                ('Subject', models.CharField(max_length=122)),
                ('Format', models.CharField(max_length=122)),
                ('Date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pgSenator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='studentExecutivebodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='ugSenator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
