# Generated by Django 4.1 on 2023-01-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_alter_ugsenator_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcomingEventlead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
