# Generated by Django 4.1 on 2023-01-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_upcomingeventlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='Title',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='upcomingeventlead',
            name='Title',
            field=models.DateTimeField(null=True),
        ),
    ]
