# Generated by Django 4.1 on 2023-01-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_upcomingevent_title_upcomingeventlead_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='Title',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='upcomingeventlead',
            name='Title',
            field=models.DateField(null=True),
        ),
    ]
