# Generated by Django 4.1 on 2023-01-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_upcomingevent_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingevent',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='upcomingeventlead',
            name='Title',
        ),
    ]
