# Generated by Django 4.1 on 2023-01-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_remove_upcomingevent_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='upcomingeventlead',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
